<?php
declare(strict_types=1);

/**
 * Pratham Car Care — database backup script.
 *
 * Run locally:   php db/backup.php
 * On Hostinger:  php db/backup.php   (or schedule a cron job)
 *
 * Uses only PDO (no shell/exec), so it works on shared hosting.
 * Output: db/backups/{db}_{YYYY-MM-DD_HH-MM-SS}.sql
 *
 * NOTE: production credentials are read from environment variables
 * so this file can stay in git without leaking secrets.
 */

$host  = getenv('DB_HOST') ?: '127.0.0.1';
$port  = getenv('DB_PORT') ?: '3306';
$user  = getenv('DB_USER') ?: 'root';
$pass  = getenv('DB_PASS') ?: '';
$db    = getenv('DB_NAME') ?: 'pratham_care';

$dsn = "mysql:host={$host};port={$port};dbname={$db};charset=utf8mb4";
try {
    $pdo = new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_NUM,
        PDO::ATTR_TIMEOUT            => 30,
    ]);
} catch (PDOException $e) {
    fwrite(STDERR, "DB connection failed: {$e->getMessage()}\n");
    exit(1);
}

$dir = __DIR__ . '/backups';
if (!is_dir($dir) && !mkdir($dir, 0755, true)) {
    fwrite(STDERR, "Cannot create backup dir: {$dir}\n");
    exit(1);
}

$tables = $pdo->query('SHOW TABLES')->fetchAll(PDO::FETCH_COLUMN);

$file = $dir . '/' . $db . '_' . date('Y-m-d_H-i-s') . '.sql';
$fh   = fopen($file, 'w');
if ($fh === false) {
    fwrite(STDERR, "Cannot open backup file: {$file}\n");
    exit(1);
}

fwrite($fh, "-- Pratham Car Care backup — {$db} — " . date('Y-m-d H:i:s') . "\n");
fwrite($fh, "-- Generated by db/backup.php\n\n");
fwrite($fh, "SET FOREIGN_KEY_CHECKS = 0;\n\n");

foreach ($tables as $table) {
    $create = $pdo->query("SHOW CREATE TABLE `{$table}`")->fetch(PDO::FETCH_NUM);
    fwrite($fh, "DROP TABLE IF EXISTS `{$table}`;\n");
    fwrite($fh, $create[1] . ";\n\n");

    $rows = $pdo->query("SELECT * FROM `{$table}`")->fetchAll();
    if (count($rows) === 0) {
        fwrite($fh, "-- (empty)\n\n");
        continue;
    }

    $parts = [];
    foreach ($rows as $row) {
        $sql = '';
        foreach ($row as $value) {
            $sql .= ($value === null ? 'NULL,' : $pdo->quote((string) $value) . ',');
        }
        $parts[] = '(' . rtrim($sql, ',') . ')';
    }
    fwrite($fh, implode(",\n", $parts) . ";\n\n");
}

fwrite($fh, "SET FOREIGN_KEY_CHECKS = 1;\n");
fclose($fh);

echo "Backup saved: {$file}\n";
$size = filesize($file);
echo sprintf("Size: %.2f KB across %d tables\n", $size / 1024, count($tables));