import type { InvoiceDetail, Settings, DaySheet } from '../api/client'
import { formatINR, formatDate } from './format'

const REVIEW_URL = (placeId: string) =>
  `https://search.google.com/local/writereview?placeid=${encodeURIComponent(placeId)}`

export function buildReceiptText(invoice: InvoiceDetail, settings?: Settings): string {
  const total = parseFloat(invoice.total_amount) || 0
  const lines: string[] = [
    '*PRATHAM CAR CARE*',
    'Multibrand Car Service',
    'Near Vedant Mangalam, Karvenagar, Pune',
    settings?.shop_phone ? `Call: ${settings.shop_phone}` : '',
    '',
    `*M/s.* ${invoice.owner_name}`,
    `*Mob.:* ${invoice.owner_phone}`,
    `*Car No.:* ${invoice.plate_number}`,
    `*Bill No.:* ${invoice.bill_ref}`,
    `*Km.:* ${invoice.km_reading || '—'}`,
    `*Date:* ${formatDate(invoice.created_at)}`,
    invoice.next_service_km ? `Next servicing Km.: ${invoice.next_service_km}` : '',
    invoice.next_service_date ? `Next Service Date: ${invoice.next_service_date}` : '',
    '',
    '--------------------------------',
  ]

  invoice.items.forEach((it, i) => {
    lines.push(
      `${i + 1}) ${it.product_name}` +
        `   Qty ${it.quantity} x ${formatINR(it.unit_rate)} = ${formatINR(it.charged_amount)}`,
    )
  })

  lines.push('--------------------------------', `*TOTAL: ₹${formatINR(total)}*`)
  if (invoice.amount_in_words) lines.push(`Rs. in words: ${invoice.amount_in_words}`)
  lines.push('', 'Thank You...!')

  if (settings?.google_place_id) {
    lines.push('', `Rate us on Google: ${REVIEW_URL(settings.google_place_id)}`)
  }

  return lines.filter((l) => l !== '').join('\n')
}

export function openWhatsApp(phone: string, text: string): void {
  const clean = (phone || '').replace(/\D/g, '')
  if (!clean) return
  window.open(`https://wa.me/${clean}?text=${encodeURIComponent(text)}`, '_blank')
}

export function buildReminderText(reminder: { owner_name: string; plate_number: string; next_service_date: string }, settings?: Settings): string {
  const dateStr = new Date(reminder.next_service_date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })
  const lines: string[] = [
    'Dear Customer,',
    '',
    `This is a friendly reminder from *PRATHAM CAR CARE*`,
    'Your vehicle service is due.',
    '',
    `*M/s.* ${reminder.owner_name}`,
    `*Car No.:* ${reminder.plate_number}`,
    `*Service Due Date:* ${dateStr}`,
    '',
    'Please visit us or call to schedule your appointment.',
    settings?.shop_phone ? `Call: ${settings.shop_phone}` : 'Call us for appointments.',
    '',
    'Thank You!',
    '— Pratham Car Care, Karvenagar, Pune',
  ]

  if (settings?.google_place_id) {
    lines.push('', `Rate us on Google: ${REVIEW_URL(settings.google_place_id)}`)
  }

  return lines.filter((l) => l !== '').join('\n')
}

export function buildDaySheetText(sheet: DaySheet, settings?: Settings): string {
  const dateStr = formatDate(sheet.date)
  const lines: string[] = [
    `*DAY SHEET — ${dateStr}*`,
    'Pratham Car Care, Karvenagar, Pune',
    '--------------------------------',
    `*No. of Bills:* ${sheet.bills}`,
    `*Billed Total:* ₹${formatINR(sheet.billed_total)}`,
  ]

  if (sheet.items.length) {
    lines.push('', '*Services / Parts sold:*')
    sheet.items.forEach((it, i) => {
      lines.push(`${i + 1}) ${it.product_name} × ${it.qty} = ₹${formatINR(it.total)}`)
    })
  }

  lines.push('', '--------------------------------')
  if (sheet.expenses.length) {
    lines.push(`*Expenses:* ₹${formatINR(sheet.expense_total)}`)
    sheet.expenses.forEach((e) => {
      lines.push(`   • ${e.description} (${e.category}) = ₹${formatINR(e.amount)}`)
    })
  } else {
    lines.push(`*Expenses:* ₹${formatINR(0)}`)
  }
  lines.push('--------------------------------')
  lines.push(`*Net (Profit) for the day:* ₹${formatINR(sheet.net)}`)

  if (settings?.shop_phone) lines.push('', `Daily sheet auto-generated by Pratham Car Care · ${settings.shop_phone}`)

  return lines.filter((l) => l !== '').join('\n')
}

export function buildBillShareMessage(invoice: InvoiceDetail, settings?: Settings): string {
  const total = formatINR(invoice.total_amount)
  const lines: string[] = [
    'Dear Customer,',
    '',
    `Thank you for visiting *PRATHAM CAR CARE*.`,
    `Your bill no. *${invoice.bill_ref}* of ₹${total} is attached here as a PDF.`,
    invoice.next_service_date ? `Please visit us again — your next service is due on ${invoice.next_service_date}.` : '',
    invoice.next_service_km ? `Next servicing km.: ${invoice.next_service_km}` : '',
    '',
    'We value your feedback. Please rate us on Google:',
  ]

  if (settings?.google_place_id) {
    lines.push(REVIEW_URL(settings.google_place_id))
  } else {
    lines.push('Search "Pratham Car Care" on Google and leave a review.')
  }

  lines.push('', 'Thank You!', '— Pratham Car Care, Karvenagar, Pune')
  return lines.filter((l) => l !== '').join('\n')
}

export { REVIEW_URL }